export const IS_LOADING_RESERVATION = 'IS_LOADING_RESERVATION';
export const RESERVATIONS_IS_LOADED = 'RESERVATIONS_IS_LOADED';
export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const GET_RESERVATION_BY_ID = 'GET_RESERVATION_BY_ID';
