export const LOADING_RESERVATIONS = "LOADING_RESERVATIONS";
export const LOADING_RESERVATION = "LOADING_RESERVATION";
export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_RESERVATION = "GET_RESERVATION";