export const IS_LOADING_SERVICES = "IS_LOADING_SERVICES";
export const IS_LOADING_SERVICE = "IS_LOADING_SERVICE";
export const GET_SERVICE = "GET_SERVICE";
export const GET_SERVICES = "GET_SERVICES";
