export const IS_LOADING_SERVICES = "IS_LOADING_SERVICES";
export const SERVICES_IS_LOADED = "SERVICES_IS_LOADED";
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICE_BY_ID = "GET_SERVICE_BY_ID";
